# Generated by Django 4.1.7 on 2023-04-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='photo/%y/%m/%d')),
                ('datetime', models.DateTimeField()),
                ('activ', models.BooleanField(default=True)),
            ],
        ),
    ]
