# Generated by Django 4.1.7 on 2023-04-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finger',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='finger',
            name='category',
            field=models.CharField(blank=True, choices=[('id', 'id'), ('name', 'name')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='finger',
            name='image',
            field=models.ImageField(upload_to='photos/%y/%m/%d'),
        ),
    ]
