# Generated by Django 4.2 on 2023-05-08 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_finger_adress_finger_age_finger_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finger', to='products.finger')),
            ],
        ),
    ]
